# export PATH=/opt/homebrew/bin:$PATH
eval "$(/opt/homebrew/bin/brew shellenv)"


# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

if [ -z "$TMUX" ]
then
    tmux attach -t TMUX || tmux new -s TMUX
fi

export NVM_DIR="$HOME/.nvm"
# Lazy-load nvm. Sourcing nvm.sh costs ~0.75s on every shell (it auto-switches
# to the default Node via nvm_auto), which dominated split/pane startup. Defer
# it until nvm/node/npm/npx is actually used, so panes that never touch Node
# (Claude, plain shells) start instantly; the first Node use in a session pays
# the one-time load. Non-interactive shells never sourced nvm anyway, so this
# is equivalent there.
_load_nvm() {
  unset -f nvm node npm npx
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                       # loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"     # loads completion
}
for _c in nvm node npm npx; do
  eval "${_c}() { _load_nvm; ${_c} \"\$@\"; }"
done
unset _c

if [ -L ~/.zsh/alias ]; then
    source ~/.zsh/alias
else
    print "404: ~/.zsh/alias not found."
 fi

export EDITOR=vim


export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

## Enable vi mode
#  whenever you open your zsh terminal you’ll be in Insert mode. Type ESC to go into Normal mode and enjoy a trimmed down Vim experience and the most common Vim motions right within your terminal. When you’re done with your editing, type i or a to go back into Insert mode and have fun.
bindkey -v

# Abitlity to open visual studio code from terminal
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

## fixing the weird autocompletion
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Branch name now lives on the tmux pane border + status badge, so the prompt
# only flags a dirty tree: a red ✗ when there are staged, unstaged, or
# untracked changes; nothing when clean or outside a git repo.
function git_prompt_dirty() {
    git rev-parse --is-inside-work-tree &>/dev/null || return
    [[ -n "$(git status --porcelain 2>/dev/null)" ]] && echo " ✗"
}

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
# # Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

COLOR_DEF=$'\e[0m'
COLOR_USR=$'\e[38;5;243m'
COLOR_DIR=$'\e[38;5;197m'
COLOR_GIT=$'\e[38;5;39m'
setopt PROMPT_SUBST
# export PROMPT='${COLOR_USR}%n ${COLOR_DIR}%~ ${COLOR_GIT}$(parse_git_branch)${COLOR_DEF} $ '
export PROMPT='%{%F{243}%}%n %{%F{197}%}%~%{%F{red}%}$(git_prompt_dirty)%{%F{normal}%} $%{%f%} '


# Start no duplicate history when reverse-searching my commands
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt incappendhistory
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
# End no duplicate history when reverse-searching my commands
#
# Renabling the search shortcut that doesn't work by default when the vim-mode is enabled
bindkey '^r' history-incremental-search-backward

# On slow systems, checking the cached .zcompdump file to see if it must be
# regenerated adds a noticable delay to zsh startup.  This little hack restricts
# it to once a day.  It should be pasted into your own completion file.
#
# The globbing is a little complicated here:
# - '#q' is an explicit glob qualifier that makes globbing work within zsh's [[ ]] construct.
# - 'N' makes the glob pattern evaluate to nothing when it doesn't match (rather than throw a globbing error)
# - '.' matches "regular files"
# - 'mh+24' matches files (or directories or whatever) that are older than 24 hours.

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# End case insensitive completion

source ~/zsh-plugins/fzf-tab/fzf-tab.plugin.zsh

## Helix editor
HELIX_RUNTIME=/opt/homebrew/opt/helix/runtime
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
# export PATH="$PATH:$HOME/.rvm/bin"
# Ruby
eval "$(rbenv init -)"
export GEM_HOME="$HOME/.gem"
export PATH="/usr/local/sbin:$PATH"

PATH=~/.console-ninja/.bin:$PATH

# version manager that support many languages, but added here because of Ruby
. "$HOME/.asdf/asdf.sh"

# Added by LM Studio CLI (lms)
# export PATH="$PATH:/Users/mauricio/.lmstudio/bin"
export PATH="$HOME/.local/bin:$PATH"

# Local / company-specific settings (cloud SDKs, API tokens, anything not
# personal) live outside this repo. Convention: symlink ~/.zshrc.local to
# whatever holds them. Sourced last so it can override anything above.
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
